<%@ Language=VBScript %>
<%
' getFilesFolder.asp
' JSON file/folder listing endpoint for the rebuilt Control Panel File Manager.
'
' Upload target:
'   http://winxxxx.site4now.net:830/new/getFilesFolder.asp
'
' Expected POST fields:
'   u      encrypted cp login, for example encrypted "openreward-001"
'   b      encrypted customer base path, for example encrypted "h:\root\home\openreward-001\www"
'   p      encrypted requested path. May be blank, relative ("\site1"), or absolute inside base path.
'   ts     unix timestamp generated by the new CP API
'   nonce  random request id
'   sig    sha256(u|b|p|ts|nonce|sharedSecret)
'
' Required server config:
'   Preferred: set IIS process environment variables:
'     FILE_MANAGER_ENCRYPT_KEY
'     FM_AGENT_SHARED_SECRET
'     FM_AGENT_ALLOW_SIGNED_PLAIN=1  ' temporary bridge until .NET Persits-compatible encryption is complete
'     FM_AGENT_REQUIRE_SIGNATURE=1     ' set to 0 for dev only to skip signature checks
'   Fallback: set LOCAL_ENCRYPT_KEY and LOCAL_SHARED_SECRET below on the server copy.
'
' Important:
'   Do not leave LOCAL_* values in source control.
'   Keep ALLOW_PLAIN_REQUESTS = False in production.

Option Explicit
Response.Buffer = True
Response.ContentType = "application/json"
Response.Charset = "utf-8"
On Error Resume Next
Response.TrySkipIisCustomErrors = True
On Error GoTo 0

Const MAX_ITEMS = 1000
Const TOKEN_TTL_SECONDS = 300
Const ALLOW_PLAIN_REQUESTS = False

' Server-only fallback values. Prefer IIS environment variables instead.
Const LOCAL_ENCRYPT_KEY = "fc9ad28b5f9bd8bcaa3dd0e3c5a2dce915f413b8c8934d975364a52c2272a927"
Const LOCAL_SHARED_SECRET = ""

Dim startedAt
startedAt = Timer

On Error Resume Next
Main
If Err.Number <> 0 Then
  WriteError "server_error", "Unable to list this folder.", 500
End If
On Error GoTo 0

Sub Main()
  If LCase(Trim(Request.QueryString("health") & Request.Form("health"))) = "1" Then
    WriteHealthJson
    Exit Sub
  End If

  Dim encryptedUser, encryptedBasePath, encryptedPath, ts, nonce, sig
  encryptedUser = Trim(Request.Form("u") & Request.QueryString("u"))
  encryptedBasePath = Trim(Request.Form("b") & Request.QueryString("b"))
  encryptedPath = Trim(Request.Form("p") & Request.QueryString("p"))
  ts = Trim(Request.Form("ts") & Request.QueryString("ts"))
  nonce = Trim(Request.Form("nonce") & Request.QueryString("nonce"))
  sig = Trim(Request.Form("sig") & Request.QueryString("sig"))

    If encryptedUser = "" Or encryptedBasePath = "" Then
      WriteError "bad_request", "Missing file manager credentials.", 400
      Exit Sub
    End If

    If IsSignatureRequired() Then
      If ts = "" Or nonce = "" Or sig = "" Then
        WriteError "bad_request", "Missing file manager credentials.", 400
        Exit Sub
      End If
    ElseIf encryptedPath = "" Then
      encryptedPath = ""
    End If

    If Not IsSignedRequestValid(encryptedUser, encryptedBasePath, encryptedPath, ts, nonce, sig) Then
      WriteError "unauthorized", "Invalid or expired file manager request.", 401
      Exit Sub
  End If

  Dim cpLogin, basePath, requestedPath
  cpLogin = DecodeRequestValue(encryptedUser)
  basePath = DecodeRequestValue(encryptedBasePath)
  requestedPath = DecodeRequestValue(encryptedPath)

  If cpLogin = "" Or basePath = "" Then
    WriteError "unauthorized", "Unable to decrypt file manager request.", 401
    Exit Sub
  End If

  If Not IsValidCpLogin(cpLogin) Then
    WriteError "forbidden", "Invalid hosting account identity.", 403
    Exit Sub
  End If

  Dim fso
  Set fso = Server.CreateObject("Scripting.FileSystemObject")

  Dim normalizedBase, targetPath, validationMessage
  normalizedBase = NormalizeBasePath(fso, basePath)
  If Not IsBasePathForUser(normalizedBase, cpLogin) Then
    WriteError "forbidden", "Base path must stay inside the selected hosting account.", 403
    Exit Sub
  End If

  validationMessage = ""
  targetPath = ResolveCustomerPath(fso, normalizedBase, requestedPath, validationMessage)

  If validationMessage <> "" Then
    WriteError "forbidden", validationMessage, 403
    Exit Sub
  End If

  If Not fso.FolderExists(targetPath) Then
    WriteError "not_found", "Folder does not exist.", 404
    Exit Sub
  End If

  If HasUnsafeReparsePoint(fso, normalizedBase, targetPath) Then
    WriteError "forbidden", "Folder path contains an unsafe junction or reparse point.", 403
    Exit Sub
  End If

  WriteFolderJson fso, cpLogin, normalizedBase, targetPath, startedAt
End Sub

Function IsSignedRequestValid(encryptedUser, encryptedBasePath, encryptedPath, ts, nonce, sig)
  IsSignedRequestValid = False

  If Not IsSignatureRequired() Then
    IsSignedRequestValid = True
    Exit Function
  End If

  If ALLOW_PLAIN_REQUESTS And sig = "" Then
    IsSignedRequestValid = True
    Exit Function
  End If

  Dim sharedSecret
  sharedSecret = GetSettingValue("FM_AGENT_SHARED_SECRET", LOCAL_SHARED_SECRET)
  If sharedSecret = "" Or ts = "" Or nonce = "" Or sig = "" Then Exit Function
  If Not IsNumeric(ts) Then Exit Function

  Dim nowUnix, requestUnix
  nowUnix = DateDiff("s", "01/01/1970 00:00:00", DateAdd("h", -GetTimezoneOffsetHours(), Now()))
  requestUnix = CLng(ts)

  If Abs(CDbl(nowUnix) - CDbl(requestUnix)) > TOKEN_TTL_SECONDS Then Exit Function

  Dim expectedSig
  expectedSig = LCase(Hash256(encryptedUser & "|" & encryptedBasePath & "|" & encryptedPath & "|" & ts & "|" & nonce & "|" & sharedSecret))
  IsSignedRequestValid = SecureEquals(LCase(sig), expectedSig)
End Function

Function IsSignatureRequired()
  Dim value
  value = LCase(GetSettingValue("FM_AGENT_REQUIRE_SIGNATURE", "0"))
  IsSignatureRequired = Not (value = "0" Or value = "false" Or value = "no")
End Function

Function DecodeRequestValue(value)
  DecodeRequestValue = ""
  If value = "" Then Exit Function

  Dim encryptKey
  encryptKey = LOCAL_ENCRYPT_KEY
  If encryptKey = "" Then encryptKey = GetSettingValue("FILE_MANAGER_ENCRYPT_KEY", "")
  If encryptKey = "" Then
    If AllowSignedPlainRequest() Then DecodeRequestValue = value
    Exit Function
  End If

  If Not LooksLikeHex(value) Then
    Exit Function
  End If

  DecodeRequestValue = Rc4HexDecrypt(encryptKey, value)
End Function

Function Rc4HexDecrypt(encryptKey, cipherHex)
  Dim keyBytes(), state(255), cipherBytes(), outputBytes()
  Dim i, j, x, n, keyLen, tmp, k

  keyLen = Len(encryptKey)
  If keyLen = 0 Then
    Rc4HexDecrypt = ""
    Exit Function
  End If

  ReDim keyBytes(keyLen - 1)
  For i = 1 To keyLen
    keyBytes(i - 1) = Asc(Mid(encryptKey, i, 1)) And 255
  Next

  ReDim cipherBytes((Len(cipherHex) \ 2) - 1)
  ReDim outputBytes(UBound(cipherBytes))
  For i = 0 To UBound(cipherBytes)
    cipherBytes(i) = CInt("&H" & Mid(cipherHex, (i * 2) + 1, 2))
  Next

  For i = 0 To 255
    state(i) = i
  Next

  j = 0
  For i = 0 To 255
    j = (j + state(i) + keyBytes(i Mod keyLen)) Mod 256
    tmp = state(i)
    state(i) = state(j)
    state(j) = tmp
  Next

  x = 0
  j = 0
  For n = 0 To UBound(cipherBytes)
    x = (x + 1) Mod 256
    j = (j + state(x)) Mod 256
    tmp = state(x)
    state(x) = state(j)
    state(j) = tmp
    k = state((state(x) + state(j)) Mod 256)
    outputBytes(n) = cipherBytes(n) Xor k
  Next

  Rc4HexDecrypt = Utf8BytesToString(outputBytes)
End Function

Function Utf8BytesToString(bytes)
  On Error Resume Next
  Dim stream
  Set stream = Server.CreateObject("ADODB.Stream")
  stream.Type = 1
  stream.Open
  stream.Write BytesToBinary(bytes)
  stream.Position = 0
  stream.Type = 2
  stream.Charset = "utf-8"
  Utf8BytesToString = stream.ReadText
  stream.Close
  Set stream = Nothing
  If Err.Number <> 0 Then
    Err.Clear
    Utf8BytesToString = BytesToLatin1String(bytes)
  End If
  On Error GoTo 0
End Function

Function BytesToBinary(bytes)
  Dim i, binary
  binary = ""
  For i = 0 To UBound(bytes)
    binary = binary & ChrB(bytes(i))
  Next
  BytesToBinary = binary
End Function

Function BytesToLatin1String(bytes)
  Dim i, text
  text = ""
  For i = 0 To UBound(bytes)
    text = text & Chr(bytes(i))
  Next
  BytesToLatin1String = text
End Function

Function AllowSignedPlainRequest()
  Dim value
  value = LCase(GetSettingValue("FM_AGENT_ALLOW_SIGNED_PLAIN", "0"))
  AllowSignedPlainRequest = (value = "1" Or value = "true" Or value = "yes")
End Function

Function GetSettingValue(name, fallback)
  On Error Resume Next
  Dim shell, value
  value = ""
  Set shell = Server.CreateObject("WScript.Shell")
  value = Trim(shell.Environment("PROCESS")(name) & "")
  If value = "" Then value = Trim(shell.Environment("SYSTEM")(name) & "")
  If value = "" Then value = Trim(shell.Environment("USER")(name) & "")
  Set shell = Nothing
  On Error GoTo 0

  If value = "" Then value = fallback
  GetSettingValue = value
End Function

Function DecryptText(encryptKey, keyHex)
  On Error Resume Next
  Dim CM, Context, Key, Blob2, result
  result = ""

  Set CM = Server.CreateObject("Persits.CryptoManager")
  Set Context = CM.OpenContextEx("Microsoft Enhanced RSA and AES Cryptographic Provider", "", True)
  Set Key = Context.GenerateKeyFromPassword(encryptKey, 32782, 26128)
  Set Blob2 = CM.CreateBlob
  Blob2.Hex = keyHex
  result = Key.DecryptText(Blob2)

  Set Blob2 = Nothing
  Set Key = Nothing
  Set Context = Nothing
  Set CM = Nothing

  DecryptText = result
  On Error GoTo 0
End Function

Function Hash256(toHash)
  On Error Resume Next
  Dim CM, Context, Hash
  Hash256 = ""

  Set CM = Server.CreateObject("Persits.CryptoManager")
  Set Context = CM.OpenContextEx("Microsoft Enhanced RSA and AES Cryptographic Provider", "", True)
  Set Hash = Context.CreateHash(32782)
  Hash.AddText toHash
  Hash256 = Hash.Value.Hex

  Set Hash = Nothing
  Set Context = Nothing
  Set CM = Nothing
  On Error GoTo 0
End Function

Function SecureEquals(leftValue, rightValue)
  Dim i, result
  SecureEquals = False
  If Len(leftValue) <> Len(rightValue) Then Exit Function

  result = 0
  For i = 1 To Len(leftValue)
    result = result Or (Asc(Mid(leftValue, i, 1)) Xor Asc(Mid(rightValue, i, 1)))
  Next

  SecureEquals = (result = 0)
End Function

Function LooksLikeHex(value)
  Dim i, ch
  LooksLikeHex = False
  If Len(value) < 16 Or (Len(value) Mod 2) <> 0 Then Exit Function

  For i = 1 To Len(value)
    ch = LCase(Mid(value, i, 1))
    If InStr("0123456789abcdef", ch) = 0 Then Exit Function
  Next

  LooksLikeHex = True
End Function

Function IsValidCpLogin(cpLogin)
  Dim i, ch
  IsValidCpLogin = False
  If Len(cpLogin) < 3 Or Len(cpLogin) > 80 Then Exit Function

  For i = 1 To Len(cpLogin)
    ch = LCase(Mid(cpLogin, i, 1))
    If InStr("abcdefghijklmnopqrstuvwxyz0123456789-_", ch) = 0 Then Exit Function
  Next

  IsValidCpLogin = True
End Function

Function NormalizeBasePath(fso, basePath)
  Dim value
  value = Replace(Trim(basePath), "/", "\")
  value = Replace(value, "\\?\", "")
  value = fso.GetAbsolutePathName(value)
  NormalizeBasePath = TrimTrailingSlash(value)
End Function

Function IsBasePathForUser(basePath, cpLogin)
  Dim expected, normalized
  expected = "h:\root\home\" & LCase(cpLogin)
  normalized = LCase(TrimTrailingSlash(basePath))
  IsBasePathForUser = (normalized = expected Or Left(normalized, Len(expected) + 1) = expected & "\")
End Function

Function ResolveCustomerPath(fso, normalizedBase, requestedPath, ByRef validationMessage)
  validationMessage = ""

  Dim cleanRequest
  cleanRequest = Replace(Trim(requestedPath), "/", "\")
  cleanRequest = Replace(cleanRequest, "\\?\", "")

  If cleanRequest = "" Or cleanRequest = "\" Then
    ResolveCustomerPath = normalizedBase
    Exit Function
  End If

  If InStr(cleanRequest, "..") > 0 Then
    validationMessage = "Invalid directory access."
    Exit Function
  End If

  If Left(cleanRequest, 2) = "\\" Then
    validationMessage = "UNC paths are not allowed."
    Exit Function
  End If

  If InStr(cleanRequest, ":") > 0 And Not StartsWithIgnoreCase(cleanRequest, normalizedBase) Then
    validationMessage = "Cross-drive paths are not allowed."
    Exit Function
  End If

  Dim candidate
  If StartsWithIgnoreCase(cleanRequest, normalizedBase) Then
    candidate = cleanRequest
  Else
    candidate = normalizedBase & "\" & TrimLeadingSlash(cleanRequest)
  End If

  candidate = fso.GetAbsolutePathName(candidate)

  If Not IsPathInsideBase(normalizedBase, candidate) Then
    validationMessage = "File manager path must stay inside the selected hosting account."
    Exit Function
  End If

  ResolveCustomerPath = TrimTrailingSlash(candidate)
End Function

Function IsPathInsideBase(basePath, candidatePath)
  Dim baseWithSlash, candidateWithSlash
  baseWithSlash = LCase(TrimTrailingSlash(basePath) & "\")
  candidateWithSlash = LCase(TrimTrailingSlash(candidatePath) & "\")
  IsPathInsideBase = (Left(candidateWithSlash, Len(baseWithSlash)) = baseWithSlash) Or (LCase(TrimTrailingSlash(candidatePath)) = LCase(TrimTrailingSlash(basePath)))
End Function

Function StartsWithIgnoreCase(value, prefix)
  StartsWithIgnoreCase = (Left(LCase(value), Len(LCase(prefix))) = LCase(prefix))
End Function

Function TrimTrailingSlash(value)
  Do While Len(value) > 3 And Right(value, 1) = "\"
    value = Left(value, Len(value) - 1)
  Loop
  TrimTrailingSlash = value
End Function

Function TrimLeadingSlash(value)
  Do While Left(value, 1) = "\"
    value = Mid(value, 2)
  Loop
  TrimLeadingSlash = value
End Function

Function HasUnsafeReparsePoint(fso, basePath, targetPath)
  On Error Resume Next
  HasUnsafeReparsePoint = False

  Dim rel, parts, current, i, folder
  rel = Mid(TrimTrailingSlash(targetPath), Len(TrimTrailingSlash(basePath)) + 1)
  rel = TrimLeadingSlash(rel)
  If rel = "" Then Exit Function

  parts = Split(rel, "\")
  current = TrimTrailingSlash(basePath)

  For i = 0 To UBound(parts)
    If parts(i) <> "" Then
      current = current & "\" & parts(i)
      If fso.FolderExists(current) Then
        Set folder = fso.GetFolder(current)
        If (CLng(folder.Attributes) And 1024) <> 0 Then
          HasUnsafeReparsePoint = True
          Exit Function
        End If
      End If
    End If
  Next

  Set folder = Nothing
  On Error GoTo 0
End Function

Sub WriteFolderJson(fso, cpLogin, basePath, targetPath, startedAtValue)
  Dim folder
  Set folder = fso.GetFolder(targetPath)

  Dim search, sortBy, orderBy, page, pageSize
  search = LCase(Trim(Request.Form("search") & Request.QueryString("search") & Request.Form("srch_input") & Request.QueryString("srch_input")))
  sortBy = LCase(Trim(Request.Form("sortBy") & Request.QueryString("sortBy") & Request.Form("sort_by") & Request.QueryString("sort_by")))
  orderBy = LCase(Trim(Request.Form("orderBy") & Request.QueryString("orderBy") & Request.Form("order_by") & Request.QueryString("order_by")))
  page = ToPositiveInt(Request.Form("page") & Request.QueryString("page"), 1)
  pageSize = ToPositiveInt(Request.Form("pageSize") & Request.QueryString("pageSize"), 250)
  If pageSize > MAX_ITEMS Then pageSize = MAX_ITEMS

  Dim foldersJson, filesJson, totalFolders, totalFiles, emittedFolders, emittedFiles
  foldersJson = BuildFolderArrayJson(folder, basePath, search, page, pageSize, totalFolders, emittedFolders)
  filesJson = BuildFileArrayJson(folder, basePath, search, page, pageSize, totalFiles, emittedFiles)

  Response.Write "{"
  Response.Write """success"":true,"
  Response.Write """message"":""Folder loaded."","
  Response.Write """cpLogin"":" & JsonString(cpLogin) & ","
  Response.Write """basePath"":" & JsonString(basePath) & ","
  Response.Write """currentPath"":" & JsonString(ToRelativePath(basePath, targetPath)) & ","
  Response.Write """absolutePath"":" & JsonString(targetPath) & ","
  Response.Write """parentPath"":" & JsonString(ParentRelativePath(fso, basePath, targetPath)) & ","
  Response.Write """exists"":true,"
  Response.Write """totalFolders"":" & totalFolders & ","
  Response.Write """totalFiles"":" & totalFiles & ","
  Response.Write """emittedFolders"":" & emittedFolders & ","
  Response.Write """emittedFiles"":" & emittedFiles & ","
  Response.Write """page"":" & page & ","
  Response.Write """pageSize"":" & pageSize & ","
  Response.Write """sortBy"":" & JsonString(sortBy) & ","
  Response.Write """orderBy"":" & JsonString(orderBy) & ","
  Response.Write """elapsedMs"":" & CLng((Timer - startedAtValue) * 1000) & ","
  Response.Write """folders"":" & foldersJson & ","
  Response.Write """files"":" & filesJson
  Response.Write "}"

  Set folder = Nothing
End Sub

Function BuildFolderArrayJson(folder, basePath, search, page, pageSize, ByRef total, ByRef emitted)
  Dim subFolder, json, skipped, startIndex, endIndex
  json = "["
  total = 0
  emitted = 0
  skipped = 0
  startIndex = ((page - 1) * pageSize) + 1
  endIndex = page * pageSize

  For Each subFolder In folder.SubFolders
    If search = "" Or InStr(LCase(subFolder.Name), search) > 0 Then
      total = total + 1
      If total >= startIndex And total <= endIndex Then
        If emitted > 0 Then json = json & ","
        json = json & "{"
        json = json & """name"":" & JsonString(subFolder.Name) & ","
        json = json & """relativePath"":" & JsonString(ToRelativePath(basePath, subFolder.Path)) & ","
        json = json & """size"":0,"
        json = json & """modified"":" & JsonString(FormatIsoDate(subFolder.DateLastModified)) & ","
        json = json & """created"":" & JsonString(FormatIsoDate(subFolder.DateCreated)) & ","
        json = json & """type"":""folder"","
        json = json & """isFolder"":true"
        json = json & "}"
        emitted = emitted + 1
      End If
    End If
  Next

  json = json & "]"
  BuildFolderArrayJson = json
End Function

Function BuildFileArrayJson(folder, basePath, search, page, pageSize, ByRef total, ByRef emitted)
  Dim file, json, startIndex, endIndex, ext
  json = "["
  total = 0
  emitted = 0
  startIndex = ((page - 1) * pageSize) + 1
  endIndex = page * pageSize

  For Each file In folder.Files
    If search = "" Or InStr(LCase(file.Name), search) > 0 Then
      total = total + 1
      If total >= startIndex And total <= endIndex Then
        If emitted > 0 Then json = json & ","
        ext = LCase(Mid(file.Name, InStrRev(file.Name, ".") + 1))
        If InStr(file.Name, ".") = 0 Then ext = ""
        json = json & "{"
        json = json & """name"":" & JsonString(file.Name) & ","
        json = json & """relativePath"":" & JsonString(ToRelativePath(basePath, file.Path)) & ","
        json = json & """size"":" & CLng(file.Size) & ","
        json = json & """modified"":" & JsonString(FormatIsoDate(file.DateLastModified)) & ","
        json = json & """created"":" & JsonString(FormatIsoDate(file.DateCreated)) & ","
        json = json & """extension"":" & JsonString(ext) & ","
        json = json & """type"":""file"","
        json = json & """isFolder"":false,"
        json = json & """isEditable"":" & JsonBool(IsEditableFile(ext))
        json = json & "}"
        emitted = emitted + 1
      End If
    End If
  Next

  json = json & "]"
  BuildFileArrayJson = json
End Function

Function ToRelativePath(basePath, value)
  Dim rel
  rel = Mid(TrimTrailingSlash(value), Len(TrimTrailingSlash(basePath)) + 1)
  rel = TrimLeadingSlash(rel)
  If rel = "" Then
    ToRelativePath = "\"
  Else
    ToRelativePath = "\" & rel
  End If
End Function

Function ParentRelativePath(fso, basePath, targetPath)
  If LCase(TrimTrailingSlash(basePath)) = LCase(TrimTrailingSlash(targetPath)) Then
    ParentRelativePath = ""
  Else
    ParentRelativePath = ToRelativePath(basePath, fso.GetParentFolderName(targetPath))
  End If
End Function

Function IsEditableFile(ext)
  Dim allow
  allow = "|json|js|cshtml|htaccess|ashx|cer|asax|pl|asp|ascx|aspx|php|asa|config|bas|vbs|xml|htm|html|txt|sql|css|tar|url|cfm|shtml|shtm|ssi|cs|vb|xaml|master|inc|sitemap|"
  IsEditableFile = (ext <> "" And InStr(allow, "|" & LCase(ext) & "|") > 0)
End Function

Function ToPositiveInt(value, fallback)
  If IsNumeric(value) Then
    ToPositiveInt = CLng(value)
    If ToPositiveInt < 1 Then ToPositiveInt = fallback
  Else
    ToPositiveInt = fallback
  End If
End Function

Function FormatIsoDate(value)
  FormatIsoDate = Year(value) & "-" & Pad2(Month(value)) & "-" & Pad2(Day(value)) & "T" & Pad2(Hour(value)) & ":" & Pad2(Minute(value)) & ":" & Pad2(Second(value))
End Function

Function Pad2(value)
  If CInt(value) < 10 Then
    Pad2 = "0" & CStr(value)
  Else
    Pad2 = CStr(value)
  End If
End Function

Function JsonString(value)
  JsonString = """" & JsonEscape(CStr(value)) & """"
End Function

Function JsonBool(value)
  If value Then JsonBool = "true" Else JsonBool = "false"
End Function

Function JsonEscape(value)
  value = Replace(value, "\", "\\")
  value = Replace(value, """", "\""")
  value = Replace(value, vbCrLf, "\n")
  value = Replace(value, vbCr, "\n")
  value = Replace(value, vbLf, "\n")
  value = Replace(value, vbTab, "\t")
  JsonEscape = value
End Function

Sub WriteError(code, message, statusCode)
  Response.Status = CStr(statusCode) & " " & message
  On Error Resume Next
  Response.TrySkipIisCustomErrors = True
  On Error GoTo 0
  Response.Write "{"
  Response.Write """success"":false,"
  Response.Write """code"":" & JsonString(code) & ","
  Response.Write """message"":" & JsonString(message)
  Response.Write "}"
End Sub

Sub WriteHealthJson()
  Dim sharedSecret, encryptKey
  sharedSecret = GetSettingValue("FM_AGENT_SHARED_SECRET", LOCAL_SHARED_SECRET)
  encryptKey = LOCAL_ENCRYPT_KEY
  If encryptKey = "" Then encryptKey = GetSettingValue("FILE_MANAGER_ENCRYPT_KEY", "")

  Response.Write "{"
  Response.Write """success"":true,"
  Response.Write """agent"":""getFilesFolder"","
  Response.Write """signatureRequired"":" & JsonBool(IsSignatureRequired()) & ","
  Response.Write """sharedSecretConfigured"":" & JsonBool(sharedSecret <> "") & ","
  Response.Write """encryptKeyConfigured"":" & JsonBool(encryptKey <> "") & ","
  Response.Write """signedPlainEnabled"":" & JsonBool(AllowSignedPlainRequest()) & ","
  Response.Write """serverTime"":" & JsonString(FormatIsoDate(Now()))
  Response.Write "}"
End Sub

Function GetTimezoneOffsetHours()
  ' Classic ASP has no portable UTC clock. This keeps token TTL tolerant enough for server local time.
  ' Set to 0 if the server clock is already UTC. Adjust on the server copy if needed.
  GetTimezoneOffsetHours = 0
End Function
%>
